[build]
    command = "hugo --gc --minify"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.70.0"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "hugo --gc --minify"

[context.branch-deploy]
    command = "hugo --gc --minify"
